"""instancedate

Revision ID: c16f3975dc44
Revises: 49e8eea70f47
Create Date: 2025-05-15 18:51:03.408197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16f3975dc44'
down_revision = '49e8eea70f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_date', sa.Date(), nullable=True))
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('instance_date')

    # ### end Alembic commands ###
