"""xx

Revision ID: d3ffff0cabf4
Revises: c16f3975dc44
Create Date: 2025-05-15 22:35:18.521370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ffff0cabf4'
down_revision = 'c16f3975dc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
