"""add priority

Revision ID: e802f1e7342b
Revises: 7f8bf850e9b0
Create Date: 2025-07-01 12:26:03.042626

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e802f1e7342b"
down_revision = "7f8bf850e9b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("priority", sa.Integer(), nullable=False, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
